---

- name: Make sure the requested locale exists on the server
  become: yes
  locale_gen:
    name: "{{ sansible_postgresql_locale }}"
    state: present

- name: Copy configuration templates
  become: yes
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ sansible_postgresql_version }}/main/postgresql.conf"
  notify: reload postgres

- name: Copy pg_hba.conf
  become: yes
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ sansible_postgresql_version }}/main/pg_hba.conf"
  notify: restart postgres

- name: Ensure postgresql is Running and Enabled
  become: yes
  service:
    enabled: yes
    name: postgresql
    state: started
  when: sansible_postgresql_autostart

- name: Ensure DB user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ sansible_postgresql_root_user }}"
    password: "{{ sansible_postgresql_root_password }}"
    role_attr_flags: "SUPERUSER,CREATEROLE,CREATEDB,INHERIT,login"
    state: present
  no_log: yes
  when: sansible_postgresql_autostart

- name: Ensure postgresql is Stopped and Disabled
  become: yes
  service:
    enabled: no
    name: postgresql
    state: stopped
  when: not sansible_postgresql_autostart
