---

- name: start postgres
  become: yes
  service:
    name: postgresql
    state: started
  when: sansible_postgresql_autostart

- name: reload postgres
  become: yes
  service:
    name: postgresql
    state: reloaded
  when: sansible_postgresql_autostart

- name: restart postgres
  become: yes
  service:
    name: postgresql
    state: restarted
  when: sansible_postgresql_autostart

- name: stop postgres
  become: yes
  service:
    name: postgresql
    state: stopped
