---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Install apt-transport-https, net-tools
      become: yes
      apt:
        name:
          - apt-transport-https
          - net-tools
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: postgresql
